config/routes.rb
Rails.application.routes.draw do
  get "order_items/new"
  # get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
  # Order-related routes
  resources :orders, only: [ :create, :show ]
  # Route for cart form (screen 2)
  get "orders/:id/cart", to: "order_items#new", as: :new_order_item
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy

  validates :total_value, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :total_quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_t0: 0 }

  # # def alculate_total
  # #
  # def add_products_to_order(quantity):
  #   # Adds products to the order based on the quantity the user has input.
  #   #
  #   # for every product in the table (coffee, green tea, strawb) check if the user has input a number under the quantity columng
  #   # if the quantity field is not empty,
  # end
  # end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :unit_price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def calculate_subtotal
    quantity * unit_price
  end
end

app/models/product.rb
# Represents a product in the system.
class Product < ApplicationRecord
  has_many :order_items

  validates :name, presence: true
  validates :code, presence: true, uniqueness: true
  validates :price, presence: true, numericality: { greater_than: 0 }

  # Retrieve all products from the database.
  # @return [ActiveRecord::Relation] A collection of all product records.
  def self.all_products
    all()
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def new
    @order = Order.find(params[:id])
    Rails.logger.debug("Current order: #{@order.inspect()}")
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # Create a new order with total_quantity and total_value of 0 to start.
  def create
    Rails.logger.info("calling OrdersController.create()")
    @order = Order.new(total_quantity: 0, total_value: 0)
    Rails.logger.debug("Newly created empty order #{@order.inspect()}")
   if @order.save()
     redirect_to new_order_item_path(@order), notice: "Order successfully started."
   else
    render :new, alert: "Error initializing order."
   end
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns a product instance from a collection, using its product code
  def find_by_code(collection, product_code)
    collection.find do |item|
      if item.is_a?(Product)
        item.code == product_code
      elsif item.is_a?(OrderItem)
        item.product.code == product_code
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/home/index.html.erb
<h1>Welcome</h1>
<p>Find me in app/views/home/index.html.erb</p>
<p>Please click below to start a new order.</p>

<p>
    <%= button_to 'Start order', orders_path, method: :post %>
</p> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Cash Register Ruby" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/order_items/new.html.erb
<h1>OrderItems#new</h1>
<p>Find me in app/views/order_items/new.html.erb</p>